### ISSUE TITLE
What configurations are necessary on server side ?

### ISSUE THREAD

**Issue by ghost** [dasTor/imap-acl#5]
I use Postfix/dovecot on Debian with dovecot acl plugin.. 
I see that it configure the "imap-acl" files in the user mail folder.
But for some strange reason I have another file called "imap-acl-file" that is default there for every user.
Now I have manually placed a symlink and it now writes in the imap-acl-file 
Then I shared a folder with my other user, but the question is where does the user know that a folder was shared with him ?
And how can he access it ?

**Comment by dasTor** [comment]
Did you create a namespace?
https://wiki.dovecot.org/SharedMailboxes/Shared

If it's still not working, maybe ask on the dovecot mailinglist.
